# Generated by Django 4.2 on 2023-09-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_city_lat_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
    ]
